spring:
  application:
    name: my-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10  # Intervalo de renovación de heartbeat
    lease-expiration-duration-in-seconds: 30  # Tiempo antes de que la instancia se considere caída
server:
  port: 0

